### ISSUE TITLE
Figure out how many users should be in the ERD

### ISSUE THREAD

**Issue by htdguide** [htdguide/studio3#11]

**Comment by abhistyalish2802** [comment]
So according to me their can be 6 users 
Customers - Individuals who order dumplings, either for dine-in, takeout, or delivery.
Staff Members - Including:
Chefs/Cooks - Those responsible for preparing the food items.
Cashiers - Employees who handle payment transactions at the counter for takeout orders or dine-in.
Managers - Individuals who oversee the operations of the dumpling shop, including inventory management, staff scheduling, and financial reporting.
Suppliers - While not directly interacting with the system on a daily basis, suppliers are crucial for inventory management, providing ingredients, packaging, etc.
Delivery Personnel - My dumpling shop offers a delivery option, there may be a role for delivery personnel, either in-house or through a third-party service.
