### ISSUE TITLE
Figure out user cases

### ISSUE THREAD

**Issue by htdguide** [htdguide/studio3#12]

**Comment by gaganparmar2003** [comment]
User Cases-  User can open the website and can check the products without having an account.
2. But  for ordering it have to have an Account.
3. In My profile- Current Order
- Previous Order
- Personal Information
4. Filters- As a customer i want that in a website it have to have a filter to select according to its price range and quantity.
5. Deals- As a customer i want a deals option which is in various packs of quantity.
6. No data saving for the bank information
7. Pick up and delivery options want to be avaliable
8. For Large orders like stock orders i want a separate column or page with good deals for whole stock.
9. I want a guest login without signing up as an account.
10. i want to get an confirmation email or text after my order confirm and are about to deliver.
11. i want customer service to be avaliable like faster responsive
12. i want address and personal info about the shop
13. i want location of the place like map.
14. have to have an loyality program for regular customer
15. more discounts
16. more coupns.
