### ISSUE TITLE
Find demos that illustrate idea

### ISSUE THREAD

**Issue by htdguide** [htdguide/studio3#13]

**Comment by gnijen** [comment]
![Image](https://github.com/htdguide/studio3/assets/131938107/401819f4-3afb-4fe0-88c4-50baa9cdfa14)
![Image](https://github.com/htdguide/studio3/assets/131938107/80b56016-1883-4432-8b18-32e4d76cf6c9)
![Image](https://github.com/htdguide/studio3/assets/131938107/8a2eefc2-1907-4d02-a512-182824bb046e)
![Image](https://github.com/htdguide/studio3/assets/131938107/8f20d19d-da82-4361-8cd7-00ad92a541cf)
![Image](https://github.com/htdguide/studio3/assets/131938107/325e6c46-159e-41b6-8463-36eb595e1aee)
