### ISSUE TITLE
Figma Wireframe Main Page

### ISSUE THREAD

**Issue by htdguide** [htdguide/studio3#8]

**Comment by Sahil4353** [comment]
![Image](https://github.com/htdguide/studio3/assets/125628877/3ccb56c4-80f4-4716-91b6-4b646c0cca28)

**Comment by Sahil4353** [comment]
Main Page Complete

**Comment by htdguide** [comment]
Good job Sahil! I like your wireframe

**Comment by gnijen** [comment]
well done!

**Comment by Sahil4353** [comment]
![Image](https://github.com/htdguide/studio3/assets/125628877/df0f1a1b-9079-4b6b-85a3-dbdb1388e51c)

**Comment by Sahil4353** [comment]
Main Page Complete
