### ISSUE TITLE
Figma Wireframe Cart

### ISSUE THREAD

**Issue by htdguide** [htdguide/studio3#9]

**Comment by abhistyalish2802** [comment]
![Image](https://github.com/htdguide/studio3/assets/127061939/a418461c-c129-4825-9a06-5688c4a1e724)

**Comment by abhistyalish2802** [comment]
Completed the Figma wireframe for the cart page, addressing all design requirements and feedback. Closing this issue as the wireframe is now finalized and ready for the next phase of development.
